# Generated by Django 6.0.3 on 2026-03-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône FontAwesome (ex: fas fa-seedling)", max_length=50)),
                ('valeur', models.CharField(help_text='Valeur affichée (ex: 500+, 1000 T)', max_length=100)),
                ('unite', models.CharField(blank=True, help_text='Unité (ex: Tonnes, Hectares, Producteurs)', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['ordre'],
            },
        ),
        migrations.AlterField(
            model_name='infosite',
            name='nom_cooperative',
            field=models.CharField(default='SOCOPROCAAP', max_length=200),
        ),
    ]
