# Generated by Django 6.0.3 on 2026-04-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_membreequipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(choices=[('Cacao', 'Cacao'), ('Maïs', 'Maïs'), ('Gombo', 'Gombo'), ('Élevage Porcin', 'Élevage Porcin')], max_length=100)),
                ('nom_producteur', models.CharField(max_length=200)),
                ('tonnage', models.DecimalField(decimal_places=2, help_text='en tonnes', max_digits=10)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='en hectares', max_digits=10)),
                ('session', models.CharField(help_text='ex: 2025', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-session', 'produit', 'nom_producteur'],
            },
        ),
    ]
