# Generated by Django 6.0.3 on 2026-04-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_campagne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='en hectares', max_digits=10, null=True),
        ),
    ]
